<?php
session_start();
unset($_SESSION['recisao_motivo']);
unset($_SESSION['recisao_funcionario']);
unset($_SESSION['recisao_loja']);
unset($_SESSION['recisao_data_fim_do_fim_do_aviso']);
unset($_SESSION['recisao_data_inicio_do_fim_do_aviso']);
unset($_SESSION['recisao_quantidade_itens']);
unset($_SESSION['recisao_status_funcionario']);
header("location:../painel/rescisoes.php");
?>